### ISSUE TITLE
Example on home page does not work on Ubuntu or Windows

### ISSUE THREAD

**Issue by eddy-ojb** [davidteather/TikTok-Api#100]
I think either I am not running this correctly or there is something now changed with tiktoks endpoint.

I have a fresh install of Ubuntu and tried this with and without virtualenv. Also tried on Windows. I get the following error:

```
>>> trending = api.trending(results)
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
```
Any thoughts on this?

I have followed the instructions correctly as far as I can tell and I am guessing that the endpoint is no longer valid within the code?

**Comment by davidteather** [comment]
You might want to try to install chromedriver on your environment path so the command
```
chromedriver
```
in your terminal or command prompt is registered.

**Comment by NeelDroid** [comment]
Also if you are on python3.5 or 3.6. play around with the version of `websockets`. there's a slight chance that it's messing up pyppeteer connection.

**Comment by eddy-ojb** [comment]
Thanks folks. ISssomeone able to share their pip requirements file and version of chromedriver?

chromedriver is installed in path. I also downgraded webdriver down from 8 to 6, but I got a warning that it is incompatible with pyppeteer 0.2.2.#

This also results in a new error where websockets doesn't expect 'ping_interval' as an argument to its create_connection

**Comment by eddy-ojb** [comment]
or a Dockerfile would help

**Comment by oi-eddyoj** [comment]
OK I got it to work with conda to solve dependencies for me:
Best to stick this in a new enviornment with python 3.7.
No doubt there are others to follow with the requirements file in its current state. Github won't let me upload yaml, so here it is for others:

```
`name: tiktok
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3=py_1
  - brotlipy=0.7.0=py37h4ab8f01_1000
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.14.0=py37ha419a9e_0
  - cryptography=2.9.2=py37h26f1ce3_0
  - idna=2.9=py_1
  - openssl=1.1.1g=he774522_0
  - pycparser=2.20=py_0
  - pyee=7.0.2=pyh9f0ad1d_0
  - pyopenssl=19.1.0=py_1
  - pyppeteer=0.0.25=py_1
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python_abi=3.7=1_cp37m
  - six=1.15.0=pyh9f0ad1d_0
  - tqdm=4.46.0=pyh9f0ad1d_0
  - urllib3=1.25.9=py_0
  - websockets=8.1=py37h8055547_1
  - win_inet_pton=1.1.0=py37_0
  - pip=20.0.2=py37_3
  - python=3.7.0=hea74fb7_0
  - setuptools=46.4.0=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_2
  - wheel=0.34.2=py37_0
  - wincertstore=0.2=py37_0
prefix: C:\Users\eb\Anaconda3\envs\tiktok

`
```

**Comment by davidteather** [comment]
Glad you figured it out. I'll redirect others here who have a similar issue.

**Comment by davidteather** [comment]
@eddy-ojb Does @oi-eddyoj's answer help you out?

**Comment by aspiringguru** [comment]
I have similar problems. Error message below might trick the search engines into finding this error quicker? :)  Haven't resolved the problem.
my environment : windows 10 home (up to date), Ubuntu app. conda.
chromedriver in same dir as file (also remembered chromedriver version needs to match the chrome browser version)

tried conda install TikTokApi (package not available)
- failed in ubuntu non-conda. 
- failed in windows powershell
- failed in windows cmd 

my pip freeze below. my working environment is not fresh.  will find a fresh working environment on the weekend.

pip freeze
WARNING: Could not generate requirement for distribution -ip 20.0.2 (c:\users\bmt\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages): Parse error at "'-ip==20.'": Expected W:(abcd...)
appdirs==1.4.3
asyncio==3.4.3
beautifulsoup4==4.9.1
bs4==0.0.1
certifi==2020.4.5.1
chardet==3.0.4
colorama==0.4.3
configparser==5.0.0
crayons==0.3.0
distlib==0.3.0
filelock==3.0.12
gitdb==4.0.5
GitPython==3.1.2
idna==2.9
importlib-metadata==1.5.2
numpy==1.18.3
pandas==1.0.3
pyee==7.0.2
pyppeteer==0.2.2
pyppeteer-stealth==1.0.0
python-dateutil==2.8.1
pytz==2019.3
requests==2.23.0
selenium==3.141.0
six==1.14.0
smmap==3.0.4
soupsieve==2.0.1
TikTokApi==3.1.1
tqdm==4.46.0
urllib3==1.25.9
virtualenv==20.0.14
webdriver-manager==2.5.1
websockets==8.1
zipp==3.1.0


>>> trending = api.trending(results)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bmt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\TikTokApi\tiktok.py", line 72, in trending
    b = browser(api_url)
  File "C:\Users\bmt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\TikTokApi\browser.py", line 27, in __init__
    asyncio.get_event_loop().run_until_complete(self.start())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\bmt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\TikTokApi\browser.py", line 30, in start
    self.browser = await pyppeteer.launch(self.options)
  File "C:\Users\bmt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyppeteer\launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\bmt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyppeteer\launcher.py", line 147, in launch
    self.cmd, **options, )
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 14001] The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail

**Comment by davidteather** [comment]
What does it say if you run “chromedriver” in your cmd

**Comment by aspiringguru** [comment]
I have other code running selenium and using chromedriver. (I do automation and data collection via python selenium often)


Starting ChromeDriver 81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

**Comment by davidteather** [comment]
I'm not really sure what's wrong then, sorry.

**Comment by oi-eddyoj** [comment]
Recommend a fresh install in a VM

**Comment by davidteather** [comment]
I’m going to close because I can’t replicate. If you want an example that sets up and works on Ubuntu check the travis.yml and the prescript commands. I’ve also got it running fine on windows.
