### ISSUE TITLE
Notify when someone posts

### ISSUE THREAD

**Issue by JonoLeviaThan** [davidteather/TikTok-Api#109]
I want the bot to be able to notify in a channel when someone uploads a video to TikTok, Does this API do that? Only asking because thats what the bot is for. Sorry if this is kinda a dumb question , I'm really new to making bots and I dont know much about them

**Comment by davidteather** [comment]
Sorry this api doesn’t have support for notification on upload. 

But what you can do is have a continuously running script that stores the most recent video object in a variable. 

Every x minutes you can recheck that latest video and if it doesn’t match that variable you can do whatever you need with that data because it means that user uploaded a new tiktok.
