### ISSUE TITLE
Keeping browser session open?

### ISSUE THREAD

**Issue by kicks66** [davidteather/TikTok-Api#208]
Hi there,

I've just started running this amazing package after switching over from the node-based carcabot package. One of the things i've noticed with this package is that a new browser session is being opened up on every request. I was wondering if its possible to make a modification to keep the same browser open and therefore increase the frequency of requests that can be made as well as reduce overall resource consumption?

**Comment by davidteather** [comment]
This is on my todo list for this repository, but it's annoying due to the asynchronous nature of puppeteer / pyppeteer and dealing with keeping references to the browsers while using different asyncio threads is proving to be difficult.

**Comment by davidteather** [comment]
I'm most likely going to end up using playwright for this because it allows for synchronous calls, however I'm waiting for more stealth evasions to be developed. I haven't tested making calls on playwright python yet so it could be fine. Might experiment with it around thanksgiving and for sure around winter break.

**Comment by davidteather** [comment]
Fixed! [V3.7.0](https://github.com/davidteather/TikTok-Api/releases/tag/V3.7.0) this switch may have broken your code. It's been acting a little weird on ubuntu code test servers
