### ISSUE TITLE
RapidApi Down (NO LONGER MAINTAINED)?

### ISSUE THREAD

**Issue by d1alogo** [davidteather/TikTok-Api#404]
The paid subscription to this api in rapidapi.com has been returning 504 GATEWAY_TIMEOUT for two days now.
It is marked as (NO LONGER MAINTAINED) in the dashboard.

What does all this mean? Did you drop the rapidapi service? did you drop this repository maintenance too?
Please let us now about the future of this proyect.
Thanks in advance.

**Comment by demon071** [comment]
If you use api to download video without logo you can use this free api https://api.wppress.net/tiktok/nwm/6864786214835342593

**Comment by AphroMad** [comment]
But if we want to do something else ? like getting all the videos of a particular user, how can we do that ?

**Comment by demon071** [comment]
you can try [api](https://github.com/demon071/Tiktok-API-Python)

**Comment by davidteather** [comment]
I haven't had time to maintain the rapidapi to an acceptable standard since the introduction of captchas on TikTok. So I'm dropping support as it's unstable as it feels wrong providing a service that's hardly working. 

This repository I will still be making updates to and potentially one day I will reopen the rapidapi, however that would not be in the near future.

**Comment by d1alogo** [comment]
Thanks for being sincere.
