### ISSUE TITLE
Page doesn't load

### ISSUE THREAD

**Issue by UsmanGorsii** [davidteather/TikTok-Api#45]
**Describe the bug**

Using the simple code example given on your github I tried to run the script, everything works but after opening the link, it does not load the page content. It is stuck on the loading screen

**The buggy code**

from tiktok import TikTokapi
api = TikTokapi("mypath")
api.trending(10)

**Expected behavior**

it should load the trending videos but it is stuck on  loading screen
![image](https://user-images.githubusercontent.com/48323011/71677908-b81d4080-2da5-11ea-8b8b-7901d7bfe1b2.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - version-79.0.3945.88
**Additional context**

Please let me know if we can somehow make it load the page, I have tried many methods to somehow make it work but still no luck. I hope you can suggest something or update your code here to make it work.

**Comment by davidteather** [comment]
What does it say in your console? It’s not supposed to actually load the tiktoks on the page

**Comment by davidteather** [comment]
Closing due to passing tests and no follow up

**Comment by Quintenvw** [comment]
@davidteather I'm getting this issue too. It does the same thing for me, it actually opens the browser too.
It gives me this in the console:
`[7216:4608:0129/195355.665:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -202`
It opens the tiktok page with http instead of https and thus gives an error.

**Comment by Quintenvw** [comment]
Seems more like a browsermob problem but still...
http://uwu.sk/u/64.png
