### ISSUE TITLE
[BUG] - playwrights runs in multitudes

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#464]
My code is essentially is a loop over

```
tt = api.getTikTokById(video['id'],proxy=proxy,custom_did=custom_did)
bytes = api.get_Video_By_TikTok(tt['itemInfo']['itemStruct'],proxy=proxy,custom_did=custom_did)
```

api get created in the begin of the program.

Due to some reason, playwrights did not stop and runs until the program finishes. They merrily eats all CPU and memory, at number of 20-30 they causes my machine to hang.

Actually, after some processing, it yields

```
6816498522741918981 info...loading...6816498522741918981 is video/mp4...done.
6813478929186245893 info...loading...Error at 90 Protocol error (Runtime.enable): The page has been closed. loading 6813478929186245893 error.
6830234382377258245 info...Error at 90 Target page, context or browser has been closed loading 6830234382377258245 error.
```

And after stop I still see

```
tarkhil     9917  0.0  0.0   6892  1704 ?        SNs  14:03   0:00 /bin/bash /home/tarkhil/.cache/ms-playwright/webkit-1383/pw_run.sh --inspector-pipe --headless --no-startup-window --proxy=socks5://148.xxx.xxx.247:1080
tarkhil     9922  0.5  0.0 104291544 3176 ?      SNl  14:03   0:12 /home/tarkhil/.cache/ms-playwright/webkit-1383/minibrowser-wpe/bin/MiniBrowser --inspector-pipe --headless --no-startup-window --proxy=socks5://148.xxx.xxx.247:1080
```

Should I reinint API on each run and kill all subprocesses after?...

**Comment by pibvbp** [comment]
same here

**Comment by davidteather** [comment]
Yeah right now the package has a persistent browser that exists as long as the class is initialized. You should be able to do del api if you want the browser to stop then reinitialize it later

**Comment by tarkhil** [comment]
Right now it feels like a browser is spawned per request and never gets 
stopped until the program run. Getting TikTokApi instance out of scope 
does not help.

I'll try to jury rig something tomorrow, but it's  near impossible now 
to fetch more than 3-5 videos in a single run

**Comment by Exzentttt** [comment]
Has anyone figured out the problem? class.__del__(), del - not worked for me.

**Comment by zoopzorp** [comment]
This happens because a new BrowserContext is [created](https://github.com/davidteather/TikTok-Api/blob/084bd74aedbcda1a9f63e613887b8aef70b00fbe/TikTokApi/browser.py#L116) upon each request and never closed. I am not sure if a new context is needed each time or not, but to fix the current issue keeping functionality the same:

- Return the context from `create_page` instead of a page
- Change the two calls to `create_page` to instead create the page there
- Call context.close() after the operation finishes (You will have to reorder the operations in `create_page` since the current `page.close()` is [after](https://github.com/davidteather/TikTok-Api/blob/084bd74aedbcda1a9f63e613887b8aef70b00fbe/TikTokApi/browser.py#L204) the return statement

**Comment by pibvbp** [comment]
Any chance you can post the correct code?

Plus, do you know why when trying to run the code in a jupyter-lab it complains about being able to run one playwright at a time? (works for me only with ipython).

**Comment by zoopzorp** [comment]
> Any chance you can post the correct code?

[Opened a PR](https://github.com/davidteather/TikTok-Api/pull/482)

> Plus, do you know why when trying to run the code in a jupyter-lab it complains about being able to run one playwright at a time? (works for me only with ipython).

No, but maybe this fix will fix that issue

**Comment by pibvbp** [comment]
great - thanks!!
