### ISSUE TITLE
get_video_no_watermark issue

### ISSUE THREAD

**Issue by MohammadBMelhem** [davidteather/TikTok-Api#466]
<script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">
<br/>
<br/>
<br/>
"pageProps":{"key":"6910298199769009414","serverCode":200,"statusCode":0,"statusMsg":"","itemInfo":{"itemStruct":{"id":"6910298199769009414","desc":"Wishing you Merry #Christmas with my ultimate #dessert recipe ! Enjoy Gx #Christmas2020 #holidaytreats #tiktokcooks","createTime":1608929192,"video":{"id":"6910298199769009414"
<br/>
<br/>
<br/>
https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=6910298199769009414&line=0&ratio=default&media_type=4&vr_type=0

<br/>
<br/>
<br/>
Response:
<br/>
<br/>
<br/>
HEAD>
	TITLE>Invalid URL/TITLE>
/HEAD>
<br/>
<br/>
<br/>
BODY>
	H1>Invalid URL/H1>
	The requested URL "[no URL]", is invalid.<p>
		Reference #9.4f398bd5.1610230361.9b75cf94
/BODY>

**Comment by davidteather** [comment]
TikTok patched the ability to download videos without watermarks for now

**Comment by xKRUTOIx** [comment]
@davidteather Hello, thanks for your awesome library, tried it a few days ago and it was working just fine and today started implementing my project and faced an error. Since my problem is very related to not create many topics gonna post it here.

I'm also experiencing a problem with `get_video_no_watermark` but with different error, it responds me with status `200` but without data (I checked it by manually printing response object, altough the part of the function that builds `cleanVideo` url works fine).

This is what I get when I call the function with `return_bytes=1`

```
Traceback (most recent call last):
  File "/Users/...", line 11, in <module>
    video_bytes = api.get_video_no_watermark(link, return_bytes=1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/TikTokApi/tiktok.py", line 1480, in get_video_no_watermark
    if r.text[0] == '{':
IndexError: string index out of range
```


I have two questions:
1) since TikTok patched this ability is there any workaround how to get a video without watermark for now? 
2) do you have a plan to fix it?

**Comment by davidteather** [comment]
1. I don’t know of any workaround 
2. Can’t fix if there’s no workarounds
