### ISSUE TITLE
how to create _signature because this is important parameter to get data from API

### ISSUE THREAD

**Issue by umeshdepale** [davidteather/TikTok-Api#50]

**Comment by davidteather** [comment]
This _signature element is supposed to auto-generate, but the TikTok servers are detecting selenium at the moment and that's why the API is broken. I will be looking into fixing this issue more than I already have in the upcoming days.

If you want to do this by hand you can go to the trending page of TikTok and go to the Network tab and find something of a request that looks like m.tiktok.com/list? after the question marks, there will be a parameter in the URL called _signature= copy everything after the = and you can pass that in as a parameter and it might end up working fine.
