### ISSUE TITLE
Getting list of followers

### ISSUE THREAD

**Issue by Amirh24** [davidteather/TikTok-Api#51]
Hi,
is it possible or will it be possible in the near future the get the list of the user's followers? @davidteather 
Thanks

**Comment by davidteather** [comment]
It is currently not possible, but I may add it in the future. My current focus is fixing the API as it is currently broken.

**Comment by JonMacPhers** [comment]
Hey David, I've also been working on fixing my TikTok Scraper over the past few weeks since I'm assuming they made a security update making doing so a lot more difficult. Would you like to compare notes? Perhaps 2 heads are better than 1

**Comment by davidteather** [comment]
@JonMacPhers Yeah sounds like a good idea. I also think they made some security changes on their website. 

I'm still able to successfully get a _signature attribute using browser mob proxy, but I think they changed a server side thing that makes sure your response is completely valid. Before the update, It took a few attempts to spam their servers to get a response. I figure that's what they fixed. I may have to go back to a TikTok scraper with selenium rather than getting responses from their database.

**Comment by JonMacPhers** [comment]
Heyo David I just downloaded and setup your API scraper code today and I
guess your in the process of giving Selenium a go?

Before they changed whatever they changed I was able to scrape all the
videos on a page after waiting for them to load in a loop using Selenium.

However now it seems whenever I access TikTok through Selenium's driver
window; the video listview never loads. So I was doing a bit of research
and wonder if they are maybe checking for Selenium webdriver automated
visits and denying them access to content.

I'm kind of stumped in terms of what to try next, I saw maybe trying
Selenium with IE. I'm also wondering if maybe a more obscure web driver
library might be a solution.

Were you successful in getting video feed data with browsermob at all?

Apologies in advance for any typos, I'm replying to you pretty late before
I wake up for a trip but I'm eager to figure this out 👌

**Comment by davidteather** [comment]
I was successful earlier in the year before they changed stuff but it seems like I can’t do much anymore with selenium. I also believe they are doing some kind of selenium detecting script, but I can’t seem to find a way to make sure selenium doesn’t emit any indicators that it’s a web driver

**Comment by JonMacPhers** [comment]
Yeah I'm in the same boat pretty much, I read online that it might have
something to do with this company Distil Networks, but it also could be
another company. The main thing is they all defend against Selenium,
because it's the standard. Soooo yeah the only solutions I can think of
are; we figure out how to disguise Selenium, or we shop around for a new
web driver library.

Both pretty unfortunate options when we both had this working a few weeks
ago 😅

I'll do some reading tomorrow and see if I can make any progress on this.
Please let me know if you make any breakthroughs.

**Comment by muke5hy** [comment]
I am on the same boat, I started 2 days back with selenium no matter parameter I change, video list never loads. 

If you guys find any solution please post.

**Comment by nguyenminhduc110392** [comment]
I found this scraping tool, i checked and it still can scraping tik-tok site.
https://www.getscrapio.com/
But I dont know what method they used

**Comment by davidteather** [comment]
I can't seem to find a way to get a list of user followers. I can only see the number at least from desktop view. So I'm going to close this issue for now.

**Comment by ialiman** [comment]
... and May 7th 2020 will be remembered as a sad day. RIP

**Comment by novitae** [comment]
> I can't seem to find a way to get a list of user followers. I can only see the number at least from desktop view. So I'm going to close this issue for now.

this might help you
[https://github.com/xh211314/TikTok-API/blob/3d24e9c9c5bbdd84838cd291b95e5949a70df52f/TikTokAPI.py](https://github.com/xh211314/TikTok-API/blob/3d24e9c9c5bbdd84838cd291b95e5949a70df52f/TikTokAPI.py)

**Comment by gbiz123** [comment]
I am launching a TikTok follower scraper called Toughdata. It scrapes follower lists and all their data including videos. There is a no-code option and an API. Here is the website: https://www.toughdata.net/

I am currently giving beta testers free access in exchange for feedback/testimonials. If anyone is interested in participating, please send an email to g.bizup@gmail.com
