### ISSUE TITLE
downloading multiple videos

### ISSUE THREAD

**Issue by Ckatalay** [davidteather/TikTok-Api#540]
I'm kinda new to Python so I'm sorry if this is a stupid question.
I'm trying to download multiple videos but it keeps fetching only one of them. Here is the code:

from TikTokApi import TikTokApi
import string
import random
verifyFp = "verify_kmfdq078_oRMZrX7f_0xLC_4kVO_8RJg_E1CpY5pZGgH2"
did = ''.join(random.choice(string.digits) for num in range(19))
results = 5
api = TikTokApi.get_instance(custom_verifyFp=verifyFp, use_test_endpoints=True, custom_did=did)
tiktoks = api.trending(count=results)
video = api.get_Video_By_TikTok(tiktoks[0])
for tiktok in tiktoks:
    with open("{}.mp4".format(tiktoks[0]['id']), "wb") as output:
        output.write(video)

**Comment by wallypop** [comment]
First, remove your verifyFp token as that is like a password for your account.

Second, there's a couple of issues with your code. First, when you reference tiktoks[0], you are referencing the item at the first position in the list. Think of the response from tiktok as a grocery list (it's called an array, or hash depending on the language and use)

tiktoks
- tiktok wow i'm so cool
- tiktok something will smith is doing
- tiktok a prank on someones wife
- tiktok silhouette challenge
- tiktok some new dance craze

If you reference tiktoks[0] you're referencing only the top one, "wow i'm so cool". What you want to do is reference each one. To make it easier to get more tiktoks, instead of referencing each one individually, you can do a for loop. This means for each of the items in the tiktoks list, name it tiktok, and then run the below code. This is where you want to get your video, and then write it with a name equal to the tiktok id (or whatever you want, you could name it with the user's name and do all sorts of things with it). Here's your code fixed up a bit:

`
from TikTokApi import TikTokApi
import string
import random
verifyFp = "verify_Removed"
did = ''.join(random.choice(string.digits) for num in range(19))
results = 5
api = TikTokApi.get_instance(custom_verifyFp=verifyFp, use_test_endpoints=True, custom_did=did)
tiktoks = api.trending(count=results)

for tiktok in tiktoks:
    video = api.get_Video_By_TikTok(tiktok)
    with open("{}.mp4".format(tiktok['id']), "wb") as output:
        output.write(video)
`

I'd also recommend putting some output in there so you know what's going on while it is running:

`
from TikTokApi import TikTokApi
import string
import random
verifyFp = "verify_Removed"
did = ''.join(random.choice(string.digits) for num in range(19))
results = 5
print("Creating an API instance...")
api = TikTokApi.get_instance(custom_verifyFp=verifyFp, use_test_endpoints=True, custom_did=did)
tiktoks = api.trending(count=results)
print("Got back " + str(len(tiktoks)) + " tiktoks)
print("Looping through each")
for tiktok in tiktoks:
    video = api.get_Video_By_TikTok(tiktok)
    print("Writing the video...")
    with open("{}.mp4".format(tiktok['id']), "wb") as output:
        output.write(video)
print("Done getting videos!")
`

Hope that helps!

**Comment by davidteather** [comment]
Yeah that code should do it, although verifyFp isn’t a unique parameter to your account it’s based on Unix time stamp of your session (although this may have changed since I looked at it months ago)
