### ISSUE TITLE
get comments on tik tok videos

### ISSUE THREAD

**Issue by MuhammedEminK** [davidteather/TikTok-Api#663]
get comments on tik tok videos

**Comment by adampot** [comment]
i dont think they are a get comment in this
api

**Comment by PhanNN** [comment]
I think we can. But we need to provide some required fields (verifyFp, device, coookie, msToken, X-Bogus, ...)
and change some line of code to allow this tool can get video comments

**Comment by aimadnet** [comment]
![Screenshot at 2021-09-09 12-39-04](https://user-images.githubusercontent.com/6409664/132679311-3b2e2c8d-575a-4ab1-95e6-07897644a279.png)

To get API Key: https://scraptik.com

```
import requests

url = "https://scraptik.p.rapidapi.com/list-comments"

querystring = {"aweme_id":"6944028931875949829","count":"10","cursor":"0"}

headers = {
    'x-rapidapi-host': "scraptik.p.rapidapi.com",
    'x-rapidapi-key': "xxxxxxxxxxxxxxxxxxxxxxxxxx"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)
```

**Comment by davidteather** [comment]
Stale issue

**Comment by jaybiz911** [comment]
> I think we can. But we need to provide some required fields (verifyFp, device, coookie, msToken, X-Bogus, ...) and change some lines of code to allow this tool can get video comments
> 
> You can check my fork: https://github.com/PhanNN/TikTok-Api

Hi PhanNN is this still working? I looked into your fork but had no luck

**Comment by PhanNN** [comment]
@jaybiz911: yes, I'm still getting comments from Tiktok
you should get cookie object from your account and put into get_comments.py script 
you can check my example 

![Screen Shot 2022-03-23 at 09 09 32](https://user-images.githubusercontent.com/11443776/159609440-4c3d5436-03ac-4bde-9380-e6cf6e90ceee.png)

**Comment by PhanNN** [comment]
You can inspect tiktok web page, find "share/discover" network call 
![image](https://user-images.githubusercontent.com/11443776/161178037-263eb5f0-5c17-411c-acf5-bde6be9c110d.png)

**Comment by jaybiz911** [comment]
Hi PhanNN, thanks for sharing that. I think there is a bug in your fork with the request in get_data, where "r" is not defined. So I tried to define r:

        r = requests.get(
            url,
            headers=headers,
            cookies=self.get_cookies(**kwargs),
            proxies=self.__format_proxy(proxy),
            **self.requests_extra_kwargs,
        )

but of course "headers" is not defined. I tried both your "additional_headers" which didn't work since its just an empty dict at that point (it's not going into the required log-in if statement for some reason) and also tried hardcoding the headers (using my actual tiktok cookies) directly in get_data. The best I can get is an empty-ish response:

{statusCode: 0,comments: [],cursor: 20,has_more: 0,reply_style: 2,total: 0}

but as you can see the comments are just empty! I guess this is progress compared to "blocked" which I was getting before...

Any chance you might be able to upload your most recent get_data to your fork and possibly a text version of the image you sent? For the latter, it would make it easier to go line-by-line and make sure I have all the required cookies.

thanks so much,
Jay

**Comment by PhanNN** [comment]
Hi @jaybiz911 
You can checkout my new code. I updated the way to get comment. 
See the below image

**Comment by jaybiz911** [comment]
Excellent!! it is working! I've spent many hours on this so thanks for your help PhanNN! Time to have some fun :)

**Comment by bravma** [comment]
@PhanNN Thank you very much for sharing! Helped me a lot! :-)

**Comment by PhanNN** [comment]
@jaybiz911 @bravma 
I’m very glad to hear that

If you can, pls give my folk 1 star to support other

Thank you
