### ISSUE TITLE
[BUG] - by_username not working suddenly

### ISSUE THREAD

**Issue by snoooopy-ch** [davidteather/TikTok-Api#757]
Hello, everyone.

I used this api when I need TikTok info.
But 10 days ago, this api does not work.

Would you tell me the reason why it doesn't?
Would you tell me the way how I should it?

Thanks!

**Comment by Incher25** [comment]
It seems like TikTok sometimes returns page of a different structure instead of expected user page. So TikTokApi's __extract_tag_contents() method can't parse it and get_user() method throws TikTokCaptchaError() but its not because of captcha actually. Here is current code of the __extract_tag_contents():
```
    def __extract_tag_contents(self, html):
        nonce_start = '<head nonce="'
        nonce_end = '">'
        nonce = html.split(nonce_start)[1].split(nonce_end)[0]
        j_raw = html.split(
            '<script id="__NEXT_DATA__" type="application/json" nonce="%s" crossorigin="anonymous">'
            % nonce
        )[1].split("</script>")[0]
        return j_raw
```
As you can see it tries to parse json with user data by '<head nonce="' string, but the page that Tiktok returns does not contain this string. If you take a look to the html-code  of this page you'll probably find something like "<script id="sigi-persisted-data">window['SIGI_STATE']={"AppContext": ...". So window['SIGI_STATE'] variable contains user data but it has different structure than object inside '<script id="__NEXT_DATA__" type="application/json" nonce="%s" crossorigin="anonymous">' tag.

**Comment by davidteather** [comment]
[V4.1.0](https://github.com/davidteather/TikTok-Api/releases/tag/V4.1.0) should fix this
