### ISSUE TITLE
List of trending sounds

### ISSUE THREAD

**Issue by nickmorell** [davidteather/TikTok-Api#77]
Hello, 

Would it be possible to implement an API request in order to grab the trending sounds with data associated with that sound? I know the method you have now does not grab the sound due to an incorrect signature. I'm not familiar with the signatures but if there is a new endpoint to get it I can try implementing it into the project.

**Comment by davidteather** [comment]
Yeah I'm working on trying to fix those methods. I'm not really sure what the issue is as the api just returns a blank response. I ported the signature generating method from another api and have opened an issue with their code to see if they're able to fix the issue.

I've elaborated a little bit more on what I think the problem is on [this](https://github.com/carcabot/tiktok-signature/issues/39) issue.

**Comment by davidteather** [comment]
Added with discoverMusic() in the new update. Upgrade with the following command.

```
pip install TikTokApi --upgrade
```
