### ISSUE TITLE
user.videos(count=x) will not return the correct count.

### ISSUE THREAD

**Issue by Jheesbrough** [davidteather/TikTok-Api#827]
`user.videos(count=x)` always returns 30 or higher, and there is an upper bound

As in example
```
user = api.user(username='therock')
for video in user.videos(count=100):
    print(video.id)
```
will still return 70 results.

replacing that with 
```
user = api.user(username='therock')
for video in user.videos(count=3):
    print(video.id)
```
will now return 30 results again

**Comment by davidteather** [comment]
I think the upper bound on therock might be because therock only has 70 videos. You can check if this is the case by passing `logging_level=logging.INFO` (I think) to `TiktokApi()`

I'm going to self assign myself to this issue but I'm not sure if I'll fix the lower bound or not, justification against
* the lower bound is a single "page" of results so it's not making more requests or more expensive to get the extra 27 results in your example
* would lead to more messy code in the package

justification for
* probably would lead to more messy code by the users of the library managing it than the extra mess in the package code itself

I haven't fully made up my mind about it yet
