### ISSUE TITLE
[BUG] - ModuleNotFoundError: No module named 'TikTokApi'

### ISSUE THREAD

**Issue by PolusX** [davidteather/TikTok-Api#872]
** from TikTokApi import TikTokApi **

I reinstalled TikTokApi, Python. Error remained

 - OS: Windows 10
 - TikTokApi Version 5.1.1

**Comment by anouci** [comment]
Try in a virtualenv

**Comment by imenyoo2** [comment]
i installed it in pipenv and i have the same issue

**Comment by JavierEspinMegias** [comment]
I deleted the package manually and reinstalled via pip, then worked.

**Comment by upneetsb** [comment]
tried deleting and reinstalling, tried cloning the repo. still not working. please fix asap. thanks!

**Comment by ekkyarmandi** [comment]
tried to pip install and get this message from my terminal "The system cannot find the file specified"

**Comment by alzeric** [comment]
I have the TikTokAPI added in my modules folder of my script like this, instead of pip installed (for portability reasons)

**_Folder Structure of My Script_**
```
ROOT
      [Modules Folder]
               [TikTokApi]
```

then in _**Modules/TikTokApi/__init__.py**_ file comment out everything like this (or just make it empty)
```
"""
.. include:: ../README.md

__docformat__ = "restructuredtext"

from TikTokApi.tiktok import TikTokApi
"""
```

then in my main.py call it like 
`from modules.TikTokApi.tiktok import TikTokApi`

**Comment by GrahamboJangles** [comment]
Run the script like this `python -m examples.user_example.py`
